config/routes.rb
Rails.application.routes.draw do
  resources :pictures
  resources :comments
  root 'pictures#index'
  post '/pictures' => 'pictures#upload_image'
end

app/models/comment.rb
class Comment < ActiveRecord::Base
  belongs_to :picture
  validates :text, presence: true
end

app/models/picture.rb
class Picture < ActiveRecord::Base

  has_many :comments, dependent: :destroy

  has_attached_file :image,
                    source_file_options: {all: '-auto-orient'},
                    styles: {medium: "300x300>", thumb: "100x100>"}
  validates_attachment_content_type :image, :content_type => ["image/jpg", "image/jpeg", "image/png", "image/gif"]

  before_post_process :check_file_size

  def check_file_size
    valid?
    errors[:image_file_size].blank?
  end

  def create_image_data
    data = ::EncodeUtils.pull(self.url)
    data.first[1]['data']
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/comments_controller.rb
class CommentsController < ApplicationController

  #POST /comments
  def create
    @comment = Comment.new(comment_params)
      if @comment.save
      end
    redirect_to :back
  end


  private
  def comment_params
    params.require(:comment).permit(:text, :picture_id)
  end


end

app/controllers/pictures_controller.rb
require 'json'

class PicturesController < ApplicationController
  before_action :set_picture, only: [:show, :edit, :update, :destroy]

  # GET /pictures
  # GET /pictures.json
  def index
    @pictures = Picture.all
  end

  # GET /pictures/1
  # GET /pictures/1.json
  def show
  end

  # GET /pictures/new
  def new
    @picture = Picture.new
  end

  # POST /pictures
  # POST /pictures.json
  def create

    if !params['picture'].present?
      redirect_to :back
      return
    end

    @picture = Picture.new(picture_params)

    file_params = params['picture']
    file_name = file_params['image'].original_filename
    file_name = ::EncodeUtils.form_name(file_name)

    @picture.url = file_name

    respond_to do |format|
      if @picture.save
        format.html { redirect_to "/pictures/#{@picture.url}", notice: 'Picture was successfully created.' }
        format.json { render :show, status: :created, location: @picture }
      else
        format.html { render :new }
        format.json { render json: @picture.errors, status: :unprocessable_entity }
      end
    end
  end


  # DELETE /pictures/1
  # DELETE /pictures/1.json
  def destroy
    @picture.destroy
    respond_to do |format|
      format.html { redirect_to pictures_url, notice: 'Picture was successfully destroyed.' }
      format.json { head :no_content }
    end
  end


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_picture
      @picture = Picture.find_by(:url => params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def picture_params
      params.require(:picture).permit(:image, :uploaded, :url, :score)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/comments_helper.rb
module CommentsHelper
end

app/helpers/pictures_helper.rb
module PicturesHelper
end

app/views/layouts/_messages.html.erb
<%# Rails flash messages styled for Bootstrap 3.0 %>
<% flash.each do |name, msg| %>
  <% if msg.is_a?(String) %>
    <div class="alert alert-<%= name.to_s == 'notice' ? 'success' : 'danger' %>">
      <button type="button" class="close" data-dismiss="alert" aria-hidden="true">&times;</button>
      <%= content_tag :div, msg, :id => "flash_#{name}" %>
    </div>
  <% end %>
<% end %>

app/views/layouts/_navigation.html.erb
<%# navigation styled for Bootstrap 3.0 %>
<nav class="navbar navbar-inverse navbar-fixed-top">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <%= link_to 'Home', root_path, class: 'navbar-brand' %>
    </div>
    <div class="collapse navbar-collapse">
      <ul class="nav navbar-nav">
        <%= render 'layouts/navigation_links' %>
      </ul>
    </div>
  </div>
</nav>

app/views/layouts/_navigation_links.html.erb
<%# add navigation links to this file %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title><%= content_for?(:title) ? yield(:title) : "Picture Service" %></title>
    <meta name="description" content="<%= content_for?(:description) ? yield(:description) : "Picture Service" %>">
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track' => true %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>
  <body>
    <header>
      <%= render 'layouts/navigation' %>
    </header>
    <main role="main" class=".container">
       <%= render 'layouts/messages' %>
       <%= yield %>
    </main>
  </body>
</html>

app/views/pictures/_form.html.erb
<%= form_for(@picture) do |f| %>
  <% if @picture.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@picture.errors.count, "error") %> prohibited this picture from being saved:</h2>

      <ul>
      <% @picture.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :uploaded %><br>
    <%= f.datetime_select :uploaded %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :score %><br>
    <%= f.number_field :score %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pictures/edit.html.erb
<h1>Editing Picture</h1>

<%= render 'form' %>

<%= link_to 'Show', @picture %> |
<%= link_to 'Back', pictures_path %>

app/views/pictures/index.html.erb
<div class="container">
  <div class="row">


    <div class="col-sm-2"></div>
    <div class="col-sm-8">

      <div class="page-header">
        <h1>Hour Gallery <span class="glyphicon glyphicon-globe"></span><small> One hour saves.</small></h1>
      </div>

      <% @pictures.each do |picture| %>
          <div class="col-lg-3 col-md-4 col-xs-6 gallery">
            <%= link_to picture_url(picture.url) do %>
                <%= image_tag picture.image.url(:thumb), class: 'img-responsive center-block img-thumbnail', alt: 'asd' %>
            <% end %>

          </div>
      <% end %>

    </div>
    <div class="col-sm-2"></div>
  </div>


  <div class="row">
    <div class="col-sm-2"></div>
    <div class="col-sm-8">
      <div class="panel">
        <div class="form-group">
          <div class="panel-body">

            <%= bootstrap_form_for(Picture.new) do |f| %>
                <%= f.file_field :image %>
                <%= f.submit 'Upload' %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="col-sm-2"></div>
  </div>

</div>

app/views/pictures/new.html.erb
<h1>New Picture</h1>

<%= render 'form' %>

<%= link_to 'Back', pictures_path %>

app/views/pictures/show.html.erb
<div class="container">

  <div class="row">
    <div class="col-sm-4"></div>
    <div class="col-sm-4">


    </div>
    <div class="col-sm-4"></div>
  </div>

  <div class="row">
    <div class="gallery_view">
      <p>
        <%= link_to @picture.image.url do %>
            <%= image_tag @picture.image.url %>
        <% end %>
      </p>
    </div>
  </div>
  <div class="row">
    <div class="col-sm-2"></div>
    <div class="col-sm-8">
      <div class="well">
        <dl>
          <dt>Name:</dt>
          <dd><%= @picture.image_file_name %></dd>
          <br>
          <dt>Type:</dt>
          <dd><%= @picture.image_content_type %></dd>
          <br>
          <dt>Size:</dt>
          <dd><%= @picture.image_file_size %> bytes</dd>
        </dl>
      </div>
      <% @picture.comments.each do |comment| %>
          <div class="panel panel-default">
            <div class="panel-body">
              <b><%= comment.text %></b>
              <br>
              <%= comment.created_at.strftime("%d.%m.%y - %H:%M") %>
            </div>
          </div>
      <% end %>
      <%= bootstrap_form_for(Comment.new) do |f| %>
          <%= f.text_area :text %>
          <%= f.hidden_field :picture_id, :value => @picture.id %>
          <%= f.submit 'Comment' %>
      <% end %>
    </div>
    <div class="col-sm-2"></div>
  </div>
  <div class="row"><br></div>
  <div class="row">
    <div class="col-sm-4"></div>
    <div class="col-sm-4">
    </div>
    <div class="col-sm-4"></div>
  </div>
</div>